Add subject/body separator validation
The subject and body should be separated by a blank line.

diff --git a/template/hooks/commit-msg b/template/hooks/commit-msg
--- a/template/hooks/commit-msg
+++ b/template/hooks/commit-msg
@@ -38,6 +38,9 @@ while IFS='' read -r line || [[ -n "$line" ]]; do
     if (( "$line_count" == 0 )) && (( "${#line}" > "$MAX_SUBJECT_LENGTH" )) && [[ "$line" != \#* ]]; then
         echo "error: the subject must be less than or equal to $MAX_SUBJECT_LENGTH characters" >&2
         exit 1
+    elif (( "$line_count" == 1 )) && (( "${#line}" > "0" )) && [[ "$line" != \#* ]]; then
+        echo "error: the subject and body must be separated by a blank line" >&2
+        exit 1
     elif (( "${#line}" > "$MAX_BODY_LENGTH" )) && [[ "$line" != \#* ]]; then
         corrected+="$(echo "$line" | fold -w "$MAX_BODY_LENGTH" -s)\n"
         ok=false
