Fix squash tag
Commits are prefixed with `squash!` not `autosquash!` when they are
eligible for autosquashing.

diff --git a/template/hooks/pre-push b/template/hooks/pre-push
--- a/template/hooks/pre-push
+++ b/template/hooks/pre-push
@@ -66,7 +66,7 @@ while read local_ref local_sha remote_ref remote_sha; do
 		fi
 
 		# Check for WIP commit
-		commit=`git rev-list -n 1 --grep 'fixup!' --grep 'autosquash!' "$range"`
+		commit=`git rev-list -n 1 --grep 'fixup!' --grep 'squash!' "$range"`
 		if [[ -n "$commit" ]]; then
 			if [[ "$remote_sha" == "$z40" ]]; then
 				hint_sha="$remote"
@@ -74,8 +74,8 @@ while read local_ref local_sha remote_ref remote_sha; do
 				hint_sha=`git rev-parse --short "$remote_sha"`
 			fi
 
-			echo "error: unfinished fixup! or autosquash! found. Aborting push." >&2
-			echo "hint: try 'git rebase -i --autosquash $hint_sha'" >&2
+			echo "error: unfinished fixup! or squash! found. Aborting push." >&2
+			echo "hint:  try 'git rebase -i --autosquash $hint_sha'" >&2
 			exit 1
 		fi
 	fi
